# Generated by Django 4.0.6 on 2022-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoami',
            name='now_time',
            field=models.CharField(default=(2022, 7, 9, 9, 57, 59, 5, 190, 0), max_length=12),
        ),
    ]
