# Generated by Django 4.0.6 on 2022-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_whoami_now_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoami',
            name='ip_adress',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='whoami',
            name='now_time',
            field=models.CharField(max_length=255),
        ),
    ]
