# Generated by Django 4.0.6 on 2022-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_whoami_ip_adress_alter_whoami_now_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoami',
            name='now_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
