# Generated by Django 4.0.6 on 2022-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_whoami_now_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoami',
            name='ip_adress',
        ),
        migrations.AddField(
            model_name='whoami',
            name='ip_adres',
            field=models.CharField(default='', max_length=16, verbose_name='IP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whoami',
            name='now_time',
            field=models.TimeField(auto_now=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='whoami',
            name='user_agent',
            field=models.CharField(max_length=255, verbose_name='User Agent'),
        ),
    ]
