# Generated by Django 4.0.6 on 2022-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Randomm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=100, verbose_name='Length')),
                ('digits', models.BooleanField(default=False, verbose_name='Digits is on')),
                ('specials', models.BooleanField(default=False, verbose_name='Specials is on')),
            ],
        ),
    ]
