version: "3.3"
services:
  rabbitmq:
    image: rabbitmq
    env_file: envs/rabbitmq.env

  client:
    image: node:16.14.2
    volumes:
      - ./client:/src
    command: /bin/bash -c "cd /src/; npm i; npm run dev"
    ports:
      - 5137:5137

  postgres-db:
    image: postgres
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: edonssfall/imdb
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
      - ./static:/static
    env_file:
      - envs/db.env
      - envs/rabbitmq.env
      - envs/.env

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
    ports:
      - 8000:80

volumes:
  pgdata: {}
  static: {}
