version: "3.3"
services:
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=edonssfall_db
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: edonssfall/dz
    links:
      - postgres-db:db
    volumes:
      - .:/django_app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
    ports:
      - 8000:8000

volumes:
  pgdata: {}