# Generated by Django 4.0.6 on 2022-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_year_alter_person_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(null=True, verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.DateField(null=True, verbose_name='Death Year'),
        ),
    ]
