# Generated by Django 4.0.6 on 2022-07-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_person_birth_year_alter_person_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(verbose_name='Is Adult'),
        ),
    ]
