# Generated by Django 4.0.6 on 2022-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_is_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Is Adult'),
        ),
    ]
