# Generated by Django 4.0.6 on 2022-07-17 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_is_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None, verbose_name='Characters'),
        ),
    ]
