# Generated by Django 4.0.6 on 2022-07-17 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_personmovie_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, null=True, size=None, verbose_name='Characters'),
        ),
    ]
