# Generated by Django 4.0.6 on 2022-07-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_personmovie_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmovie',
            name='characters',
        ),
    ]
